version: '3.4'

services:
  californianhealthapp:
    image: ${DOCKER_REGISTRY-}californianhealthapp
    build:
      context: .
      dockerfile: CalifornianHealthApp/Dockerfile
    depends_on:
      - booking-api
    ports:
      - "5000:80"

  booking-api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Booking.API/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"